// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SignMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PTMUserSignUpRequest_Platform

typedef GPB_ENUM(PTMUserSignUpRequest_Platform) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PTMUserSignUpRequest_Platform_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PTMUserSignUpRequest_Platform_Android = 0,
  PTMUserSignUpRequest_Platform_Ios = 1,
};

GPBEnumDescriptor *PTMUserSignUpRequest_Platform_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PTMUserSignUpRequest_Platform_IsValidValue(int32_t value);

#pragma mark - PTMSignMessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PTMSignMessageRoot : GPBRootObject
@end

#pragma mark - PTMUserSignUpRequest

typedef GPB_ENUM(PTMUserSignUpRequest_FieldNumber) {
  PTMUserSignUpRequest_FieldNumber_DeviceId = 1,
  PTMUserSignUpRequest_FieldNumber_Brand = 2,
  PTMUserSignUpRequest_FieldNumber_Platform = 3,
  PTMUserSignUpRequest_FieldNumber_OsVersion = 4,
  PTMUserSignUpRequest_FieldNumber_SdkVersion = 5,
};

@interface PTMUserSignUpRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *brand;

@property(nonatomic, readwrite) PTMUserSignUpRequest_Platform platform;

@property(nonatomic, readwrite, copy, null_resettable) NSString *osVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sdkVersion;

@end

/**
 * Fetches the raw value of a @c PTMUserSignUpRequest's @c platform property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PTMUserSignUpRequest_Platform_RawValue(PTMUserSignUpRequest *message);
/**
 * Sets the raw value of an @c PTMUserSignUpRequest's @c platform property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPTMUserSignUpRequest_Platform_RawValue(PTMUserSignUpRequest *message, int32_t value);

#pragma mark - PTMUserSignUpResponse

typedef GPB_ENUM(PTMUserSignUpResponse_FieldNumber) {
  PTMUserSignUpResponse_FieldNumber_Token = 1,
};

@interface PTMUserSignUpResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
