// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sign.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Sign.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - PTMSignRoot

@implementation PTMSignRoot

@end

#pragma mark - PTMSignRoot_FileDescriptor

static GPBFileDescriptor *PTMSignRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - PTMHelloRequest

@implementation PTMHelloRequest

@dynamic greeting;

typedef struct PTMHelloRequest__storage_ {
  uint32_t _has_storage_[1];
  NSString *greeting;
} PTMHelloRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "greeting",
        .dataTypeSpecific.className = NULL,
        .number = PTMHelloRequest_FieldNumber_Greeting,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PTMHelloRequest__storage_, greeting),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PTMHelloRequest class]
                                     rootClass:[PTMSignRoot class]
                                          file:PTMSignRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PTMHelloRequest__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PTMHelloResponse

@implementation PTMHelloResponse

@dynamic reply;

typedef struct PTMHelloResponse__storage_ {
  uint32_t _has_storage_[1];
  NSString *reply;
} PTMHelloResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "reply",
        .dataTypeSpecific.className = NULL,
        .number = PTMHelloResponse_FieldNumber_Reply,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PTMHelloResponse__storage_, reply),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PTMHelloResponse class]
                                     rootClass:[PTMSignRoot class]
                                          file:PTMSignRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PTMHelloResponse__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
